config/routes.rb
Rails.application.routes.draw do
  resources :advices
  resources :projects
  resources :cards

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}

  root 'cards#index'

  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/cards' => 'users#cards', as: :user_cards
  get 'users/:id/projects' => 'users#projects', as: :user_projects
  get 'users/:id/advices' => 'users#advices', as: :user_advices
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, S3Uploader

  has_many :cards
  has_many :projects
  has_many :advices
  # 사용자가 삭죄될 경우 has_many 관계에 있는 애들을 어떻게 해줄지설정이 필요합니다. Null 또는 삭제
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
    @user.save
    @user.avatar_url0 = @user.avatar.url
    @user.save
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :cards, :projects, :advices]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/cards
  def cards
    @page = @user.cards.page(params[:page]).per(10)
    @cards = @user.cards.order(created_at: :desc).page(@page.current_page).per(@page.limit_value)
  end

  # GET /users/1/projects
  def projects
    @page = @user.projects.page(params[:page]).per(10)
    @projects = @user.projects.order(created_at: :desc).page(@page.current_page).per(@page.limit_value)
  end

  # GET /users/1/advices
  def advices
    @page = @user.advices.page(params[:page]).per(10)
    @advices = @user.advices.order(created_at: :desc).page(@page.current_page).per(@page.limit_value)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_show_header.html.erb
<div class="container" style="margin-top: 20px;">

  <div class="card bg-light" style="width: 100%; padding: 0.5rem;">
    <div class="d-flex align-items-center">
      <div class="d-flex justify-content-left">
        <img class="card-img-top" src="<%= @user.avatar %>" alt="avatar" style="border-radius: 100%; width: 10rem; height: 10rem;">
      </div>
      <p><%= @user.nickname %></p>
    </div>
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link active" href="<%= user_cards_path %>">내 카드</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= user_projects_path %>">내 집들이</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= user_advices_path %>">내 노하우</a>
      </li>
    </ul>
  </div>
</div>

app/views/users/advices.html.erb
<%= render 'users/show_header' %>

<div class="container" style="margin-top: 20px;">
  <%= render 'layouts/page_bar', path: advices_path %>

  <% @advices.each_with_index do |m, idx| %>
    <% if idx % 3 == 0 %>
      <div class="row" style="margin-bottom: 20px;">
    <% end %>
    <div class="col-4">
      <div class="card">
        <div class="card border-white">
          <a href="<%= advice_path(m) %>" style="color: inherit;">
            <img class="card-img" style="padding: 0.5rem; height: 300px; object-fit: cover;" src="<%= m.cover_url0 %>" alt="Advice image cap">
            <div class="card-img-overlay d-flex align-items-center" style="margin: 0.5rem; background-color: rgba(0, 0, 0, 0.3)">
              <div class="card-body text-light">
                <h4 class="card-title text-center"><%= m.title %></h4>
                <div class="text-center">
                  <img src="<%= m.user.avatar_url0 %>" class="rounded-circle" style="display: inline-block; width: 2rem; height: 2rem;" alt="avatar" onerror="this.src='https://orig00.deviantart.net/9b06/f/2012/034/d/2/facebook_avatar___pikachu_by_heatphoenix-d4ojd5a.png'">
                  <h5 class="card-title" style="display: inline-block;"><%= m.user.nickname %></h5>
                </div>
              </div>
            </div>
          </a>
        </div>
        <% if current_user && m.user_id == current_user.id %>
          <div class="card-body">
            <a href="<%= edit_advice_path(m) %>">수정</a>
            <a href="<%= advice_path(m) %>" data-method="delete" data-confirm="진짜?">삭제</a>
          </div>
        <% end %>
      </div>
    </div>
    <% if idx % 3 == 2 %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/cards.html.erb
<%= render 'users/show_header' %>

<div class="container" style="margin-top: 20px;">
  <%= render 'layouts/page_bar', path: cards_path %>

  <% @cards.each_with_index do |m, idx| %>
    <% if idx % 3 == 0 %>
      <div class="row" style="margin-bottom: 20px;">
    <% end %>
    <div class="col-4">
      <div class="card">
        <div class="card-header">
          <img src="<%= m.user.avatar_url0 %>" class="rounded-circle" style="display: inline-block; width: 2rem; height: 2rem;" alt="avatar" onerror="this.src='https://orig00.deviantart.net/9b06/f/2012/034/d/2/facebook_avatar___pikachu_by_heatphoenix-d4ojd5a.png'">
          <h5 class="card-title" style="display: inline-block;"><%= m.user.nickname %></h5>
        </div>
        <a href="<%= card_path(m) %>"><img class="card-img-top" style="padding: 0.5rem; height: 300px; object-fit: cover;" src="<%= m.img_url0 %>" alt="Card image cap"></a>
        <div class="card-body">
          <p class="card-text"><%= m.content %></p>
        </div>
        <% if current_user && m.user_id == current_user.id %>
          <div class="card-body">
            <a href="<%= edit_card_path(m) %>">수정</a>
            <a href="<%= card_path(m) %>" data-method="delete" data-confirm="진짜?">삭제</a>
          </div>
        <% end %>
      </div>
    </div>
    <% if idx % 3 == 2 %>
      </div>
    <% end %>
  <% end %>
</div>
<br>

app/views/users/projects.html.erb
<%= render 'users/show_header' %>

<div class="container" style="margin-top: 20px;">
  <%= render 'layouts/page_bar', path: projects_path %>

  <% @projects.each_with_index do |m, idx| %>
    <% if idx % 3 == 0 %>
      <div class="row" style="margin-bottom: 20px;">
    <% end %>
    <div class="col-4">
      <div class="card">
        <div class="card border-white">
          <a href="<%= project_path(m) %>" style="color: inherit;">
            <img class="card-img" style="padding: 0.5rem; height: 300px; object-fit: cover;" src="<%= m.cards.length >= 1 ? m.cards[0].img_url0 : '#' %>" alt="Project image cap">
            <div class="card-img-overlay d-flex align-items-center" style="margin: 0.5rem; background-color: rgba(0, 0, 0, 0.3)">
              <div class="card-body text-light">
                <h4 class="card-title text-center"><%= m.title %></h4>
                <div class="text-center">
                  <img src="<%= m.user.avatar_url0 %>" class="rounded-circle" style="display: inline-block; width: 2rem; height: 2rem;" alt="avatar" onerror="this.src='https://orig00.deviantart.net/9b06/f/2012/034/d/2/facebook_avatar___pikachu_by_heatphoenix-d4ojd5a.png'">
                  <h5 class="card-title" style="display: inline-block;"><%= m.user.nickname %></h5>
                </div>
              </div>
            </div>
          </a>
        </div>
        <% if current_user && m.user_id == current_user.id %>
          <div class="card-body">
            <a href="<%= edit_project_path(m) %>">수정</a>
            <a href="<%= project_path(m) %>" data-method="delete" data-confirm="진짜?">삭제</a>
          </div>
        <% end %>
      </div>
    </div>
    <% if idx % 3 == 2 %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render 'users/show_header' %>