config/routes.rb
Rails.application.routes.draw do
  resources :advices
  resources :projects
  resources :cards

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}

  root 'cards#index'

  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/cards' => 'users#cards', as: :user_cards
  get 'users/:id/projects' => 'users#projects', as: :user_projects
  get 'users/:id/advices' => 'users#advices', as: :user_advices
end

app/views/layouts/_page_bar.html.erb
<p>총 개수 : <%= @page.total_count %></p>
<nav>
  <ul class="pagination justify-content-center">
    <% unless @page.first_page? %>
      <li class="page-item">
        <a class="page-link" href="<%= "#{path}?page=#{@page.prev_page}" %>" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="<%= "#{path}?page=#{@page.current_page - 1}" %>"><%= @page.current_page - 1 %></a>
      </li>
    <% end %>
    <li class="page-item active">
      <a class="page-link" href="<%= "#{path}?page=#{@page.current_page}" %>"><%= @page.current_page %></a></li>
    <% unless @page.last_page? %>
      <li class="page-item">
        <a class="page-link" href="<%= "#{path}?page=#{@page.current_page + 1}" %>"><%= @page.current_page + 1 %></a>
      </li>
      <li class="page-item">
        <a class="page-link" href="<%= "#{path}?page=#{@page.next_page}" %>" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bucket2015</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>

<body>
<div class="container" style="margin-top: 20px;">
  <div class="btn-group" role="group">
    <% if user_signed_in? %>
      <!--      <img src="<%#= current_user.avatar %>" class="rounded-circle" style="width:50px; height: 50px; border: 1px solid lightgray;" alt="avatar">-->
      <a href="<%= destroy_user_session_path %>" data-method="delete" class="btn btn-secondary" role="button">로그아웃</a>
      <a href="<%= user_path(current_user) %>" class="btn btn-secondary" role="button">마이페이지</a>
      <a href="<%= new_card_path %>" class="btn btn-secondary" role="button">새 카드</a>
      <a href="<%= new_project_path %>" class="btn btn-secondary" role="button">새 집들이</a>
      <a href="<%= new_advice_path %>" class="btn btn-secondary" role="button">새 노하우</a>
    <% else %>
      <a href="<%= new_user_session_path %>" class="btn btn-secondary" role="button">로그인</a>
      <a href="<%= new_user_registration_path %>" class="btn btn-secondary" role="button">회원가입</a>
    <% end %>
  </div>

  <p><%= notice %></p>
  <p><%= alert %></p>

  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link<%= ' active' if request.path == cards_path %>" href="<%= cards_path %>">사진피드</a>
    </li>
    <li class="nav-item">
      <a class="nav-link<%= ' active' if request.path == projects_path %>" href="<%= projects_path %>">집들이피드</a>
    </li>
    <li class="nav-item">
      <a class="nav-link<%= ' active' if request.path == advices_path %>" href="<%= advices_path %>">노하우피드</a>
    </li>
  </ul>
</div>

<%= yield %>

<!-- Optional JavaScript -->
<!-- 먼저 jQuery가 오고 그 다음 Popper.js 그 다음 Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>